#!/bin/bash

set -ex

if [[ -z $DOCKER_IMAGE ]]; then
  if [[ -n $1 ]]; then
    DOCKER_IMAGE=$1
  elif hash buildkite-agent 2>/dev/null; then
    DOCKER_IMAGE=$(buildkite-agent meta-data get docker-image)
  fi
fi

if [[ -z $DOCKER_IMAGE ]]; then
  echo "Docker image argument is required (repo/of/image:version); or set the DOCKER_IMAGE env var."
  exit 1
fi

IMAGE_TAG=$(echo $DOCKER_IMAGE | awk -F: '{print $2}')

echo '--- updating fleet service template'
perl -p -i -e "s/^Environment=VERSION=.+$/Environment=VERSION=${IMAGE_TAG}/" papertrail@.service

fleetctl destroy papertrail@.service
fleetctl submit papertrail@.service

echo '--- (re-)starting fleet service instances'
for i in {1..3}; do
  fleetctl destroy papertrail@$i
  fleetctl start papertrail@$i
  # TODO: Use consul to see if papertrail@$i is healthy yet before moving on
done
