#!/bin/bash

set -ex

echo '--- checking deploy branch'
if [[ $CI = "true" && "$BUILDBOX_BRANCH" != "$DEPLOY_BRANCH" ]]; then
  echo "Not deploying $BUILDBOX_BRANCH because only $DEPLOY_BRANCH is deployed"
  exit 0
fi

DEPLOY_USER=deploy

function usage() {
  echo -e "Usage:\n\ndeploy docker_image\n\nEx: deploy quay.io/democracyworks/papertrail:latest"
}

echo '--- retrieving repo and tag'
if [[ -z "$DOCKER_IMAGE" ]]; then
  if [[ -n "$1" ]]; then
    DOCKER_IMAGE=$1
  elif hash buildbox-agent 2>/dev/null; then
    DOCKER_IMAGE=$(buildbox-agent build-data get docker-image)
  fi
fi

if [[ -z "$DOCKER_IMAGE" ]]; then
  usage
  exit 1
fi

deploy_hosts=(docker1-int.turbovote.org docker2-int.turbovote.org)

for host in ${deploy_hosts[@]}; do
  echo "--- deploying to $host"
  scp -o StrictHostKeyChecking=no $(dirname $0)/remote_deploy $DEPLOY_USER@$host:
  ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$host "PAPERTRAIL_PORT=$PAPERTRAIL_PORT DOCKER_IMAGE=$DOCKER_IMAGE ./remote_deploy"
done
